# Generated by Django 2.2.10 on 2021-04-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0004_auto_20210407_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('dataNascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('endereco', models.CharField(max_length=1000)),
                ('cep', models.CharField(max_length=8)),
                ('cpf', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=20)),
                ('emailInstitucional', models.EmailField(max_length=200)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Campus')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Cidade')),
            ],
            options={
                'db_table': 'pessoa',
                'abstract': False,
            },
        ),
    ]
