# Generated by Django 2.2.10 on 2021-04-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servidor',
        ),
    ]
