# Generated by Django 2.2.10 on 2021-04-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20210407_2147'),
        ('geral', '0003_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Campus'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Cidade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=20, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='dataNascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='emailInstitucional',
            field=models.EmailField(max_length=200, null=True, verbose_name='Email Institucional'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(max_length=1000, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipoPessoa',
            field=models.CharField(choices=[('S', 'Servidor'), ('A', 'Aluno'), ('O', 'Outros')], max_length=1, null=True),
        ),
    ]
