# Generated by Django 2.2.10 on 2021-04-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20210407_2147'),
        ('geral', '0004_auto_20210409_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=1024, verbose_name='Descrição')),
                ('portaria', models.CharField(blank=True, max_length=20, verbose_name='Portaria')),
                ('dataCriacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dataExpiracao', models.DateField(verbose_name='Data Expiração')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='Status')),
                ('publico', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Grupo Publico')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Campus')),
            ],
            options={
                'db_table': 'grupo_trabalho',
            },
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Campus'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Cidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='emailInstitucional',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Institucional'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipoPessoa',
            field=models.CharField(blank=True, choices=[('S', 'Servidor'), ('A', 'Aluno'), ('O', 'Outros')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='ParticipantesGrupoTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lider', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Lider do Grupo')),
                ('grupoTrabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.GrupoTrabalho')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.Pessoa')),
            ],
            options={
                'db_table': 'participantes_grupo_trabalho',
            },
        ),
    ]
