# Generated by Django 2.2.10 on 2021-04-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0006_auto_20210412_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantesgrupotrabalho',
            name='grupoTrabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.GrupoTrabalho'),
        ),
        migrations.AlterField(
            model_name='participantesgrupotrabalho',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.Pessoa'),
        ),
    ]
