# Generated by Django 2.2.10 on 2021-04-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0007_auto_20210412_1933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantesgrupotrabalho',
            unique_together={('grupoTrabalho', 'pessoa')},
        ),
    ]
