# Generated by Django 2.2.10 on 2021-04-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0008_auto_20210412_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupotrabalho',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='participantesgrupotrabalho',
            options={'ordering': ['pessoa']},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome']},
        ),
    ]
