# Generated by Django 2.2.10 on 2021-04-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0009_auto_20210413_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RG'),
        ),
    ]
