# Generated by Django 2.2.10 on 2021-04-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0010_auto_20210414_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
