# Generated by Django 2.2.10 on 2021-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0012_pessoa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='documents/foto/%Y/%m/%d/', verbose_name='Foto'),
        ),
    ]
