# Generated by Django 4.0 on 2021-04-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cidade',
            table='cidade',
        ),
        migrations.AlterModelTable(
            name='estado',
            table='estado',
        ),
    ]
