# Generated by Django 4.0 on 2021-04-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_cidade_table_alter_estado_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('statusPublico', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
            ],
            options={
                'db_table': 'sistema',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.cidade')),
            ],
            options={
                'db_table': 'campus',
            },
        ),
    ]
