# Generated by Django 2.2.10 on 2021-04-13 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geral', '0009_auto_20210413_1804'),
        ('system', '0005_auto_20210413_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Campus')),
            ],
            options={
                'db_table': 'curso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InformacoesAlunos',
            fields=[
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='geral.Pessoa')),
                ('paevs', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Recebe PAEVs')),
            ],
            options={
                'db_table': 'informacoesAlunos',
            },
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.Curso')),
            ],
            options={
                'db_table': 'unidadeCurricular',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AcompanhamentoPedagogicoServidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataOcorrencia', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data Ocorrência')),
                ('descricao', models.CharField(max_length=1024, null=True, verbose_name='Descrição')),
                ('atendidoPor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendidoPor', to='geral.Pessoa')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidor', to='geral.Pessoa')),
                ('unidadeCurricular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedagogico.UnidadeCurricular')),
            ],
            options={
                'db_table': 'acompanhamento_pedagogico_servidor',
            },
        ),
        migrations.CreateModel(
            name='AcompanhamentoPedagogicoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataOcorrencia', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data Ocorrência')),
                ('dataAtestadoInicio', models.DateField(blank=True, null=True, verbose_name='Inicio Atestado')),
                ('dataAtestadoFim', models.DateField(blank=True, null=True, verbose_name='Final Atestado')),
                ('descricao', models.CharField(max_length=1024, null=True, verbose_name='Descrição')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='geral.Pessoa')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='geral.Pessoa', verbose_name='Atendido Por')),
            ],
            options={
                'db_table': 'acompanhamento_pedagogico_aluno',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30, verbose_name='Matricula')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.Pessoa')),
                ('unidadeCurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.UnidadeCurricular')),
            ],
            options={
                'db_table': 'matricula',
                'unique_together': {('matricula', 'aluno', 'unidadeCurricular')},
            },
        ),
        migrations.CreateModel(
            name='GrupoUnidadeCurricilarCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.Curso')),
                ('unidadeCurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.UnidadeCurricular')),
            ],
            options={
                'db_table': 'grupo_uc_curso',
                'unique_together': {('curso', 'unidadeCurricular')},
            },
        ),
    ]
