# Generated by Django 2.2.10 on 2021-04-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=500)),
                ('nacionalidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('dataNascimento', models.DateField()),
                ('rg', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('necessidadeEspcial', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=1)),
                ('raca', models.CharField(max_length=50)),
                ('ingresso', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'import_aluno',
            },
        ),
        migrations.CreateModel(
            name='ImportUnidadeCurricularesAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=500)),
                ('periodo', models.CharField(max_length=1)),
                ('situacao', models.CharField(max_length=50)),
                ('siglaUC', models.CharField(max_length=50)),
                ('nomeUC', models.CharField(max_length=200)),
                ('notaUC', models.CharField(max_length=50)),
                ('frequencia', models.CharField(max_length=50)),
                ('percentualFrenquencia', models.CharField(max_length=200)),
                ('anp', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'import_uc_aluno',
            },
        ),
    ]
