# Generated by Django 2.2.10 on 2021-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0002_importaluno_importunidadecurricularesaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='importaluno',
            name='check',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='importunidadecurricularesaluno',
            name='check',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
