# Generated by Django 2.2.10 on 2021-04-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0011_pessoa_matricula'),
        ('pedagogico', '0003_auto_20210413_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_matricula', to='geral.Pessoa'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'unidadeCurricular')},
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='matricula',
        ),
    ]
