# Generated by Django 2.2.10 on 2021-04-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0004_auto_20210414_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024, null=True, verbose_name='Nome')),
                ('statusPublico', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True, verbose_name='Público')),
            ],
            options={
                'db_table': 'tipo_ocorrencia',
            },
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogicoaluno',
            name='tipoOcorrencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedagogico.TipoOcorrencia', verbose_name='Ocorrência'),
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogicoservidor',
            name='tipoOcorrencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedagogico.TipoOcorrencia', verbose_name='Ocorrência'),
        ),
    ]
