# Generated by Django 2.2.10 on 2021-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0005_auto_20210419_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataAtendimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Atendimento'),
        ),
    ]
