# Generated by Django 2.2.10 on 2021-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0006_acompanhamentopedagogicoaluno_dataatendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentopedagogicoaluno',
            name='anexo',
            field=models.BinaryField(blank=True, null=True, verbose_name='Anexo'),
        ),
    ]
