# Generated by Django 2.2.10 on 2021-04-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0007_acompanhamentopedagogicoaluno_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Anexo'),
        ),
    ]
