# Generated by Django 2.2.10 on 2021-04-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0008_auto_20210428_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompanhamentopedagogicoaluno',
            options={'permissions': (('ocorrencia_publica', 'Atendimento de ocorrência pública'), ('ocorrencia_restrita', 'Atendimento de ocorrência restrita'))},
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Anexo'),
        ),
    ]
