# Generated by Django 2.2.10 on 2021-04-30 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0012_pessoa_user'),
        ('pedagogico', '0009_auto_20210428_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.Curso')),
            ],
            options={
                'db_table': 'turma',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AcompanhamentoPedagogicoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataOcorrencia', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data Ocorrência')),
                ('descricao', models.CharField(max_length=1024, null=True, verbose_name='Descrição')),
                ('dataAtendimento', models.DateField(blank=True, null=True, verbose_name='Data Atendimento')),
                ('atendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendido', to='geral.Pessoa', verbose_name='Atendido Por')),
                ('tipoOcorrencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedagogico.TipoOcorrencia', verbose_name='Ocorrência')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma', to='pedagogico.Turma')),
            ],
            options={
                'db_table': 'acompanhamento_pedagogico_turma',
            },
        ),
    ]
