# Generated by Django 2.2.10 on 2021-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0010_acompanhamentopedagogicoturma_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='documents/acompanhamento/%Y/%m/%d/', verbose_name='Anexo'),
        ),
    ]
