# Generated by Django 2.2.10 on 2021-05-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0011_auto_20210507_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='notaFinal',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Nota Final'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='percentualFalta',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Percentual Falta'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='periodo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Período'),
        ),
    ]
