# Generated by Django 2.2.10 on 2021-05-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0012_auto_20210511_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='notaFinal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nota Final'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='percentualFalta',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Percentual Falta'),
        ),
    ]
