# Generated by Django 2.2.10 on 2021-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0013_auto_20210511_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadecurricular',
            name='periodo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Período'),
        ),
    ]
