# Generated by Django 2.2.10 on 2021-05-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0014_unidadecurricular_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, null=True, verbose_name='Situação'),
        ),
    ]
