# Generated by Django 2.2.10 on 2022-11-01 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0015_matricula_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportConselhoClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('dataImportacao', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data Importação')),
                ('unidadeCurricular', models.CharField(max_length=200)),
                ('notas', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'import_conselho_classe',
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='notaParcial',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nota Parcial'),
        ),
        migrations.AddField(
            model_name='tipoocorrencia',
            name='parecer',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True, verbose_name='Parecer'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 11, 29, 28, 605164), null=True, verbose_name='Data Ocorrência'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='tipoOcorrencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedagogico.TipoOcorrencia', verbose_name='Tipo de Atendimento'),
        ),
    ]
