# Generated by Django 2.2.10 on 2022-11-07 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0016_auto_20221101_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentopedagogicoaluno',
            name='conselho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedagogico.ImportConselhoClasse'),
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogicoturma',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='documents/acompanhamento/%Y/%m/%d/', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 10, 54, 29, 190226), null=True, verbose_name='Data Ocorrência'),
        ),
    ]
