# Generated by Django 2.2.10 on 2022-11-07 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0020_auto_20221107_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 11, 10, 19, 375246), null=True, verbose_name='Data Ocorrência'),
        ),
    ]
