# Generated by Django 2.2.10 on 2022-11-07 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0021_auto_20221107_1110'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='acompanhamentopedagogicoaluno',
        #    name='conselho',
        #),
        migrations.AddField(
            model_name='acompanhamentopedagogicoaluno',
            name='notaConselho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedagogico.ImportConselhoClasse'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 11, 10, 54, 384431), null=True, verbose_name='Data Ocorrência'),
        ),
    ]
