# Generated by Django 2.2.10 on 2022-11-08 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0022_auto_20221107_1110'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='acompanhamentopedagogicoaluno',
        #    name='notaConselho',
        #),
        migrations.AddField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataConselho',
            field=models.DateField(blank=True, null=True, verbose_name='Data Conselho'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 8, 8, 13, 38, 165943), null=True, verbose_name='Data Ocorrência'),
        ),
    ]
