# Generated by Django 2.2.10 on 2025-08-05 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0023_auto_20221108_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 5, 16, 59, 38, 105186), null=True, verbose_name='Data Ocorrência'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoturma',
            name='descricao',
            field=models.CharField(max_length=5120, null=True, verbose_name='Descrição'),
        ),
    ]
