# Generated by Django 2.2.10 on 2025-08-07 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0024_auto_20250805_1659'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='acompanhamentopedagogicoaluno',
        #    name='conselho',
        #),
        #migrations.RemoveField(
        #    model_name='acompanhamentopedagogicoaluno',
        #    name='notaConselho',
        #),
        #migrations.AddField(
        #    model_name='importconselhoclasse',
        #    name='faltas',
        #    field=models.CharField(default=0, max_length=50, null=True),
        #),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 7, 8, 40, 33, 670449), null=True, verbose_name='Data Ocorrência'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='descricao',
            field=models.CharField(max_length=5120, null=True, verbose_name='Descrição'),
        ),
    ]
