# Generated by Django 2.2.10 on 2025-08-07 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0025_auto_20250807_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 7, 8, 43, 14, 793261), null=True, verbose_name='Data Ocorrência'),
        ),
    ]
