# Generated by Django 5.2.7 on 2025-10-06 10:52

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0026_auto_20250807_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importaluno',
            old_name='check',
            new_name='check_aluno',
        ),
        migrations.RenameField(
            model_name='importunidadecurricularesaluno',
            old_name='check',
            new_name='check_aluno',
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 6, 10, 51, 54, 60565), null=True, verbose_name='Data Ocorrência'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='descricao',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Descrição'),
        ),
    ]
