# Generated by Django 5.0.14 on 2026-09-09 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0027_rename_check_importaluno_check_aluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhamentopedagogicoaluno',
            name='conselho',
        ),
        migrations.RemoveField(
            model_name='acompanhamentopedagogicoaluno',
            name='notaConselho',
        ),
        migrations.AddField(
            model_name='importconselhoclasse',
            name='faltas',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 9, 9, 9, 11, 18, 353297), null=True, verbose_name='Data Ocorrência'),
        ),
    ]
