# Generated by Django 5.0.14 on 2026-09-09 10:29

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0013_pessoa_foto'),
        ('pedagogico', '0028_remove_acompanhamentopedagogicoaluno_conselho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoConselho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Periodo')),
                ('ordem', models.IntegerField(default=1, help_text='Ordem cronológica no ano', verbose_name='Ordem de Exibição')),
                ('ativo', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Ativo')),
            ],
            options={
                'db_table': 'periodo_conselho',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataOcorrencia',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data Ocorrência'),
        ),
        migrations.AlterField(
            model_name='informacoesalunos',
            name='aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='geral.pessoa'),
        ),
        migrations.CreateModel(
            name='ConselhoClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2026, verbose_name='Ano Letivo')),
                ('dataConselho', models.DateField(default=datetime.datetime.now, verbose_name='Data de Realização')),
                ('parecerGeral', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Parecer Geral da Turma')),
                ('finalizado', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Finalizado')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conselhos_realizados', to='geral.pessoa', verbose_name='Registrado por')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.turma', verbose_name='Turma')),
                ('periodoConselho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.periodoconselho', verbose_name='Período do Conselho')),
            ],
            options={
                'db_table': 'conselho_classe',
                'ordering': ['-ano', '-dataConselho', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConselhoClasseAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Parecer Individual')),
                ('acompanhamentoGerado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_conselho', to='pedagogico.acompanhamentopedagogicoaluno', verbose_name='Registro na Ficha do Aluno')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_conselho', to='geral.pessoa')),
                ('conselho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_avaliados', to='pedagogico.conselhoclasse')),
            ],
            options={
                'db_table': 'conselho_classe_aluno',
                'unique_together': {('conselho', 'aluno')},
            },
        ),
    ]
