# Generated by Django 5.0.14 on 2026-09-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0029_periodoconselho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='periodo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Período / Fase'),
        ),
    ]
