# Generated by Django 5.0.14 on 2026-09-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0030_turma_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conselhoclasse',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('E', 'Excluído')], default='A', max_length=1, verbose_name='Status'),
        ),
    ]
