# Generated by Django 5.0.14 on 2026-09-11 14:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0013_pessoa_foto'),
        ('pedagogico', '0031_conselhoclasse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoParecerTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2026, verbose_name='Ano Letivo')),
                ('dataRegistro', models.DateField(default=datetime.datetime.now, verbose_name='Data de Registro')),
                ('observacaoGeral', models.TextField(blank=True, null=True, verbose_name='Observação Geral da Turma')),
                ('finalizado', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Finalizado')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('E', 'Excluído')], default='A', max_length=1, verbose_name='Status')),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('periodoConselho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedagogico.periodoconselho', verbose_name='Etapa / Período')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_pareceres_criadas', to='geral.pessoa', verbose_name='Responsável')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.turma', verbose_name='Turma')),
            ],
            options={
                'db_table': 'sessao_parecer_turma',
                'ordering': ['-ano', '-dataRegistro', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemParecerAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.TextField(blank=True, null=True, verbose_name='Parecer do Aluno')),
                ('acompanhamentoGerado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_sessao_parecer', to='pedagogico.acompanhamentopedagogicoaluno')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres_recebidos', to='geral.pessoa')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_parecer', to='pedagogico.sessaoparecerturma')),
            ],
            options={
                'db_table': 'item_parecer_aluno',
                'unique_together': {('sessao', 'aluno')},
            },
        ),
    ]
