# Generated by Django 5.0.14 on 2026-09-23 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0013_pessoa_foto'),
        ('pedagogico', '0032_sessaoparecerturma_itempareceraluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentopedagogicoaluno',
            name='dataExclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Exclusão'),
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogicoaluno',
            name='excluidoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompanhamentos_excluidos', to='geral.pessoa', verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogicoaluno',
            name='motivoExclusao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Exclusão'),
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogicoaluno',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('E', 'Excluído')], default='A', max_length=1, verbose_name='Status'),
        ),
    ]
