# Generated by Django 5.0.14 on 2026-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0033_acompanhamentopedagogicoaluno_dataexclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesalunos',
            name='deficiencia',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Possui Deficiência'),
        ),
    ]
