# Generated by Django 2.2.10 on 2021-05-05 18:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geral', '0012_pessoa_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'db_table': 'local',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('grupoTrabalho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geral.GrupoTrabalho', verbose_name='GrupoTrabalho')),
            ],
            options={
                'db_table': 'ged_marcadores',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('dataReuniao', models.DateField(verbose_name='Data Reunião')),
                ('duracao', models.TimeField(verbose_name='Duração')),
                ('descricao', models.CharField(max_length=200, null=True, verbose_name='Descrição')),
                ('versao', models.IntegerField(max_length=10, null=True, verbose_name='Versão')),
                ('dataCriacao', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data Criação')),
                ('pauta', models.CharField(max_length=200, null=True, verbose_name='Descrição')),
                ('registroImportacao', models.IntegerField(max_length=10, null=True, verbose_name='Registro Importação')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, null=True, verbose_name='Descrição')),
                ('grupoTrabalho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geral.GrupoTrabalho', verbose_name='GrupoTrabalho')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ged.Local', verbose_name='Local')),
                ('usuarioCriacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geral.Pessoa', verbose_name='UsuarioCriacao')),
            ],
            options={
                'db_table': 'ged_registro',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='RetificacaoRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('dataCriacao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data Reunião')),
                ('versao', models.IntegerField(max_length=10, null=True, verbose_name='Versão')),
                ('registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ged.Registro', verbose_name='Registro')),
                ('usuarioCriacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geral.Pessoa', verbose_name='UsuarioCriacao')),
            ],
            options={
                'db_table': 'ged_retificacao',
            },
        ),
        migrations.CreateModel(
            name='ParticipantesReuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, null=True, verbose_name='Descrição')),
                ('participante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geral.Pessoa', verbose_name='Participante')),
                ('registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ged.Registro', verbose_name='Registro')),
            ],
            options={
                'db_table': 'ged_participante_reuniao',
            },
        ),
        migrations.CreateModel(
            name='ParticipantesExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ged.Registro', verbose_name='Registro')),
            ],
            options={
                'db_table': 'ged_participante_externo',
            },
        ),
        migrations.CreateModel(
            name='MarcadoresRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ged.Marcador', verbose_name='Marcador')),
                ('registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ged.Registro', verbose_name='Registro')),
            ],
            options={
                'db_table': 'ged_marcador_registro',
            },
        ),
        migrations.CreateModel(
            name='Discussao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('dataCriacao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data Reunião')),
                ('registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ged.Registro', verbose_name='Registro')),
                ('usuarioCriacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geral.Pessoa', verbose_name='UsuarioCriacao')),
            ],
            options={
                'db_table': 'ged_discussao',
            },
        ),
        migrations.CreateModel(
            name='AnexosRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.FileField(upload_to='', verbose_name='Anexo')),
                ('dataAnexo', models.DateField(default=datetime.datetime.now, verbose_name='Data Reunião')),
                ('registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ged.Registro', verbose_name='Registro')),
            ],
            options={
                'db_table': 'ged_anexo',
            },
        ),
    ]
