# Generated by Django 2.2.10 on 2021-05-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='versao',
            field=models.IntegerField(null=True, verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='retificacaoregistro',
            name='versao',
            field=models.IntegerField(null=True, verbose_name='Versão'),
        ),
    ]
