# Generated by Django 2.2.10 on 2021-05-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0002_auto_20210505_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='registroImportacao',
            field=models.IntegerField(null=True, verbose_name='Registro Importação'),
        ),
    ]
