# Generated by Django 2.2.10 on 2022-06-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0003_auto_20210505_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='pauta',
            field=models.CharField(max_length=200, null=True, verbose_name='Pauta'),
        ),
    ]
